### ISSUE TITLE
[Bug] error while arp_ping : unknown

### ISSUE THREAD

**Issue by mvdwetering** [tomaae/homeassistant-mikrotik_router#199] opened 2022-05-09 19:43 UTC
## Describe the issue

Getting entries in the HA logs about arp_ping errors.
```
2022-05-09 20:54:00 ERROR (SyncWorker_9) [custom_components.mikrotik_router.mikrotikapi] Mikrotik 192.168.178.9 error while arp_ping : unknown
2022-05-09 20:54:00 DEBUG (MainThread) [custom_components.mikrotik_router.mikrotik_controller] Ping host: 192.168.178.14
2022-05-09 20:54:00 WARNING (SyncWorker_6) [custom_components.mikrotik_router.mikrotikapi] Mikrotik Reconnected to 192.168.178.9
```

## How to reproduce the issue

Not sure, I just noticed it when opening logs.

## Expected behavior

No errors

## Screenshots

not applicable

## Software versions

 - Home Assistant version: HA 2022.5.2
 - Mikrotik Router integration version:  v2.0.0 (I think, at least that is what HACS says, but manifest.json contains 0.0.0)
 - Mikrotik Hardware: RB4011iGS+5HacQ2HnD
 - RouterOS version:  7.2.1

## Diagnostics data

I don't really feel comfortable uploading it as it still has loads of ip/mac addresses in there even though some are **REDACTED**, if needed I can clean it up more.

## Traceback/Error logs

The logging as shown in the description seems to repeat every 15 seconds.
[arp_ping.log](https://github.com/tomaae/homeassistant-mikrotik_router/files/8654783/arp_ping.log)

## Additional context

Not sure what might be causing it, but I updated to RouterOS recently and I added a new router to the network. Should all be ok, but those are the things I recall changing to the network recently.

My bandwidth graphs still look fine, so integration still seems to work.

I did find some old/closed issues also mentioning arp_ping, but could not really find enough info there on where to look further now.

**Comment by tomaae** [comment] 2022-05-10 01:49
Lets first identify the culprit. What is 192.168.178.7?

Btw: what in diagnostic data makes you uncomfortable to put it here? Did I forgot to mask something sensitive?

**Comment by mvdwetering** [comment] 2022-05-10 19:05
192.168.178.7 is a Raspberry Pi which I recently disconnected since I am doing some redecorating there.
Ah, is it actually  expected that it shows those messages for disconnected devices? 
I never noticed such messages before and I have another device that is not connected on 192.168.178.101 already for a longer time and also still has a static lease.
The messages seem fishy since it seems to indicate it is reconnecting to the router at 192.168.178.9 everytime.

In the diagnostics data a lot is masked with REDACTED like values for fields like macaddress which is nice, but in other parts of diagnostics like "bridge_host", "arp", "dhcp", "client_traffic" the keys in those dictionaries are plain mac addresses which kind of negates the masking.

Like this part:
```
     "bridge_host": {
        "AA:BB:CC:DD:EE:FF": {
          "mac-address": "**REDACTED**",
          "interface": "ether2",
          "bridge": "bridge",
          "enabled": true
        },
```

**Comment by tomaae** [comment] 2022-05-12 10:03
No, you should not get that message for disconnected device. API actually reports fatal error there and causes connection to close.
Can you try to ping it from routeros using both arp and regular ping?
I will try to investigate on my side since I have few PI devices. Hopefully I can reproduce it.

Ah yes, those are tricky since they are not properties and I use mac as UID at many places as it is the best option. I plan to look into it.

**Comment by mvdwetering** [comment] 2022-05-14 15:46
Results normal ping. Number 3 seems weird as that is the router IP, pings to connected devices don't do that.
```
[admin@MikroTik Main] > ping 192.168.178.7 
  SEQ HOST                                     SIZE TTL TIME       STATUS                                                                                                                                                                                                                                                                                                            
    0 192.168.178.7                                                timeout                                                                                                                                                                                                                                                                                                           
    1 192.168.178.7                                                timeout                                                                                                                                                                                                                                                                                                           
    2 192.168.178.7                                                timeout                                                                                                                                                                                                                                                                                                           
    3 192.168.178.9                              84  64 77ms149us  host unreachable                                                                                                                                                                                                                                                                                                  
    4 192.168.178.7                                                timeout                                                                                                                                                                                                                                                                                                           
    5 192.168.178.7                                                timeout                                                                                                                                                                                                                                                                                                           
    sent=6 received=0 packet-loss=100% 
```

Results of ARP ping. It required an interface and it used to be connected to ether4, so I used that.
```
[admin@MikroTik Main] > ping arp-ping=yes interface=ether4 192.168.178.7 
  SEQ HOST                                     SIZE TTL TIME       STATUS                                                                                                                                                                                                                                                                                                           
    0                                                              ping failed                                                                                                                                                                                                                                                                                                      
    1                                                              ping failed                                                                                                                                                                                                                                                                                                      
    2                                                              ping failed                                                                                                                                                                                                                                                                                                       
    3                                                              ping failed                                                                                                                                                                                                                                                                                                       
    sent=4 received=0 packet-loss=100% 
```

**Comment by tomaae** [comment] 2022-05-14 21:28
ok, you get normal timeout now. weird.
I use following:
```        args = {
            "arp-ping": "no",
            "interval": "100ms",
            "count": 3,
            "interface": interface,
            "address": address,
        }```

**Comment by mvdwetering** [comment] 2022-05-18 19:51
I figured out how to enable the logging for `librouteros` and it seems like there is some trap(=error I guess) coming back on the ping request. The message mentions the `interace` value which is empty. I am not sure how you would provide an interface for a disconnected device since you don't really know where it is I guess.

```
2022-05-18 21:34:25 DEBUG (SyncWorker_3) [librouteros] ---> '!trap'
2022-05-18 21:34:25 DEBUG (SyncWorker_3) [librouteros] ---> '=message=ambiguous value of interface, more than one possible value matches input'
```

See file for complete output: [with_librouteros_logging.txt](https://github.com/tomaae/homeassistant-mikrotik_router/files/8720414/with_librouteros_logging.txt)

**Comment by tomaae** [comment] 2022-05-18 19:59
I see, empty interface.
```
2022-05-18 21:34:25 DEBUG (SyncWorker_4) [librouteros] <--- '/ping'
2022-05-18 21:34:25 DEBUG (SyncWorker_4) [librouteros] <--- '=arp-ping=no'
2022-05-18 21:34:25 DEBUG (SyncWorker_4) [librouteros] <--- '=interval=100ms'
2022-05-18 21:34:25 DEBUG (SyncWorker_4) [librouteros] <--- '=count=3'
2022-05-18 21:34:25 DEBUG (SyncWorker_4) [librouteros] <--- '=interface='
2022-05-18 21:34:25 DEBUG (SyncWorker_4) [librouteros] <--- '=address=192.168.178.6'
```

**Comment by tomaae** [comment] 2022-05-18 20:05
Should be fixed in master

**Comment by mvdwetering** [comment] 2022-05-19 18:05
Nice, that indeed fixed it.

**Comment by tomaae** [comment] 2022-05-19 22:48
Glad to hear that :)

**Closed** 2022-05-19 22:48 UTC
Labels: bug
