### ISSUE TITLE
[Bug] "Ignoring invalid device info" after HA 2023.8.0

### ISSUE THREAD

**Issue by Dillton** [tomaae/homeassistant-mikrotik_router#292] opened 2023-08-02 19:09 UTC
## Describe the issue
After HA upgrade to 2023.8.0 the integration will not load correctly.

## How to reproduce the issue
Update HA to 2023.8.0

## Screenshots
![image](https://github.com/tomaae/homeassistant-mikrotik_router/assets/68992112/027645bc-dac2-4836-8e7b-b3b7a539e499)
![image](https://github.com/tomaae/homeassistant-mikrotik_router/assets/68992112/874be11f-b422-4686-81e1-6254a9261bcb)

## Software versions
 - Home Assistant version: HA 2023.8.0
 - Mikrotik Router integration version: v2.1.2
 - Mikrotik Hardware: RB5009UG+S+ CRS328-24P-4S+
 - RouterOS version: 7.10.1 (stable)

## Additional context
All entities seems to be loaded under Settings->Devices&Services->Entities and usable in HA but nothing shown under Settings->Devices&Services->Devices
![image](https://github.com/tomaae/homeassistant-mikrotik_router/assets/68992112/09dbbf8f-6dc0-4fc4-a33c-48f054458de2)
![image](https://github.com/tomaae/homeassistant-mikrotik_router/assets/68992112/6a774cd1-d965-4454-add8-fba03ab48046)

**Comment by tomaae** [comment] 2023-08-02 20:54
looks like undocumented breaking change. I have reached out to ha devs so we know what is going on.

what is this actually affecting? it it just messing up linking between devices?
graph you are showing seems to be working.

I'm currently reworking whole integration, so I dont have my dev on 2023.8

**Comment by Dillton** [comment] 2023-08-02 20:58
Yeah the data under entities are present also actionable entities like buttons for turning off the firewall rules etc. seems to be working.

I would say only the linking, device vs entities is broken.

**Comment by tomaae** [comment] 2023-08-02 21:03
ok, thanks

**Comment by Dillton** [comment] 2023-08-02 21:11
Sure no problem. If you need any additional info let me know ;)

**Comment by tomaae** [comment] 2023-08-02 23:29
its caused by this PR https://github.com/home-assistant/core/pull/95641
This will require rework how device info works.

**Comment by tomaae** [comment] 2023-08-09 09:34
fixed in dev branch, not yet released

**Closed by tomaae** 2023-08-09 09:34 UTC
Labels: bug, planned

**Comment by IgorSimic** [comment] 2023-08-21 04:49
> fixed in dev branch, not yet released

Please, release it.
It is really annoying bug.
