### ISSUE TITLE
[Bug] Integration overrides names/manufacturer/model of Sonos integration

### ISSUE THREAD

**Issue by mvdwetering** [tomaae/homeassistant-mikrotik_router#57] opened 2020-08-11 19:02 UTC
## Describe the issue
The devices from the Sonos integration have their name, manufacturer and model overwritten by the Mikrotik integration. This makes it hard to identify devices since they are now all called SonosZP.

All my Sonos devices show in the device overview the following information (which comes from Mikrotik) instead of the original information.
name: SonosZP
manufacturer: MikroTik
model: RB4011iGS+5HacQ2HnD
area: Zolder
integration: Mikrotik Router, Sonos

## How to reproduce the issue
I just added the Mikrotik Router integration to my setup that already had the Sonos integration.

## Expected behavior
Information provided by "main" integration is left alone.

## Screenshots
![image](https://user-images.githubusercontent.com/732514/89937053-dfc66800-dc14-11ea-98bc-a0613a04b18d.png)

## Software versions
 - Home Assistant version: HA v0.113.3
 - Mikrotik Router integration version: 1.5.10
 - Mikrotik Hardware:  RB4011iGS+5HacQ2HnD
 - RouterOS version: 6.47.1

## Traceback/Error logs
No errors

## Additional context
Nothing to add

**Comment by tomaae** [comment] 2020-08-11 19:45
This is not related to integration. Integration properly identified device network name as it is presented on network and passed it to HA.
Why HA decided to override previous name, I dont know. Its not something I can control.
Could be that you left its default name and HA changed name to latest know name. Its something you would need to ask HA developers, but I expect this is intended behavior.
Best solution would be to change their network name to match its device name.

**Comment by mvdwetering** [comment] 2020-08-12 18:29
Unfortunately I cannot change the networkname. All Sonos devices are showing as SonosZP while their userfriendly name is different. Also I would still expect the manufacturer and model to stay from Sonos, it is not a device manufactured by Mikrotik.

However I played around a bit with the original HA Mikrotik integration and it does the same. It seems like the last integration to be installed gets to determine the name. So I will take it the the HA repo.

**Comment by mvdwetering** [comment] 2020-08-12 19:32
Ah yes, that might be a good workaround for now.

For reference, the issue I submitted in Home Assistant
https://github.com/home-assistant/core/issues/38809

**Comment by mvdwetering** [comment] 2020-08-15 13:40
Don't know if you are tracking the HA ticket, but they introduced a way for integrations to set a "default_name" and some other things for integrations like this. They updated the original Mikrotik integration, might be interesting to integrate those changes also here.

**Comment by tomaae** [comment] 2020-08-16 01:11
I see they implemented the change in HA core under PR 38829
I'm certainly interested to implement this for tracked devices. But we have to wait until it is properly released, it was just merged 3 days ago.
I will keep this issue opened so its not forgotten

**Closed** 2020-12-06 02:00 UTC
Labels: enhancement, testing
