### ISSUE TITLE
Warning being reported in HA log.

### ISSUE THREAD

**Issue by BluThunder2k** [tomaae/homeassistant-mikrotik_router#214] opened 2022-07-06 13:23 UTC
2022-07-06 09:11:45 WARNING (MainThread) [homeassistant.helpers.frame] Detected integration that uses deprecated `async_get_registry` to access entity registry, use async_get instead. Please report issue to the custom component author for mikrotik_router using this method at custom_components/mikrotik_router/mikrotik_controller.py, line 443: registry = await self.hass.helpers.entity_registry.async_get_registry()

**Comment by tjorim** [comment] 2022-07-06 16:11
Duplicate of https://github.com/tomaae/homeassistant-mikrotik_router/issues/209.

**Closed** 2022-07-06 16:54 UTC
Labels: bug, duplicate
